version: '3'

volumes: 
  pgdata: 

services:

  web:
    build:
     context: .
     dockerfile: docker/dev/python/Dockerfile 
    volumes:
      - ./app:/app
    ports:
      - 8000:8000 
    command: gunicorn --workers=5 --threads=2 youtube_helper.wsgi:application -b 0.0.0.0:8000

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=youtube_helper_db
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

