version: '3'

volumes: 
  pgdata: 

services:

  web:
    build:
     context: .
     dockerfile: docker/prod/python/Dockerfile 
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$postgres:5432/$POSTGRES_DB
    volumes:
      - ./app:/app
    ports:
      - 8000:8000 
    command: gunicorn --workers=5 --threads=2 youtube_helper.wsgi:application -b 0.0.0.0:8000

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env 
    environment:
      DB_USERNAME: $POSTGRES_USER
      DB_NAME: $POSTGRES_DB
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

