apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-helper
  labels:
    app: youtube-helper

spec:
  replicas: 1
  selector:
    matchLabels: 
      name: youtube-helper
  template:
    metadata:
      labels:
        name: youtube-helper
    spec:
      containers:
        - name: youtube-helper
          image: jacobw22/youtube-helper:1.0
          imagePullPolicy: Always
          ports: 
            - containerPort: 8000
          env:
          - name: POSTGRES_USER 
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PORT
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          - name: DJANGO_SETTINGS_MODULE
            value:  "settings.prod"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: secret-key    
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: openai-api-key
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: google-api-key
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: aws-secret-access-key
          - name: AWS_STORAGE_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: aws-storage-bucket-name
          - name: AWS_ALLOW_ORIGIN
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: aws-allow-origin
          - name: EMAIL_BACKEND
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-backend
          - name: EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-host
          - name: EMAIL_PORT
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-port
          - name: EMAIL_USE_TLS
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-use-tls
          - name: EMAIL_HOST_USER
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-host-user
          - name: EMAIL_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: email-host-password
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: spotify-client-id
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: spotify-client-secret
          - name: SPOTIFY_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: spotify-redirect-uri
          - name: SPOTIFY_USERNAME
            valueFrom:
              secretKeyRef:
                name: django-secret-env
                key: spotify-username