# Generated by Django 4.1.4 on 2023-04-07 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_storage',
            name='yt_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, size=None),
        ),
    ]
