# Generated by Django 4.1.4 on 2023-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0004_alter_user_data_storage_download_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_storage',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
