# Generated by Django 4.1.4 on 2023-07-25 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0010_user_data_storage_save_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_data_storage',
            options={'verbose_name': "User's storage", 'verbose_name_plural': "User's storage"},
        ),
        migrations.AddField(
            model_name='user_data_storage',
            name='transferred_playlists_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, size=None), default=['ss'], size=None),
            preserve_default=False,
        ),
    ]
