# Generated by Django 4.2.4 on 2023-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_data_storage',
            options={'verbose_name': "User's Storage", 'verbose_name_plural': "User's Storages"},
        ),
        migrations.AlterField(
            model_name='download_history_item',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='download_history_item',
            name='thumbnail_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='download_history_item',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filtered_comments_history_item',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filtered_comments_history_item',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prompts_history_item',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prompts_history_item',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferred_playlists_history_item',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferred_playlists_history_item',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
