# Generated by Django 4.2.4 on 2023-08-22 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0002_alter_user_data_storage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 8, 15, 412582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='filtered_comments_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 8, 15, 413582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompts_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 8, 15, 412582, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferred_playlists_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 8, 15, 413582, tzinfo=datetime.timezone.utc)),
        ),
    ]
