# Generated by Django 4.2.4 on 2023-08-31 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0002_alter_ticket_last_reset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_reset_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))),
        ),
    ]
