# Generated by Django 4.1.4 on 2023-04-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0002_user_data_storage_yt_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data_storage',
            old_name='yt_links',
            new_name='download_history',
        ),
    ]
