# Generated by Django 4.2.4 on 2023-08-22 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0003_alter_download_history_item_saved_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data_storage',
            name='download_history',
        ),
        migrations.RemoveField(
            model_name='user_data_storage',
            name='filtered_comments_history',
        ),
        migrations.RemoveField(
            model_name='user_data_storage',
            name='prompts_history',
        ),
        migrations.RemoveField(
            model_name='user_data_storage',
            name='transferred_playlists_history',
        ),
        migrations.AlterField(
            model_name='download_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 34, 26, 177175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='filtered_comments_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 34, 26, 178202, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompts_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 34, 26, 178202, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transferred_playlists_history_item',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 34, 26, 178202, tzinfo=datetime.timezone.utc)),
        ),
    ]
