# Generated by Django 4.1.4 on 2023-04-11 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0003_rename_yt_links_user_data_storage_download_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data_storage',
            name='download_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, size=None), size=None),
        ),
    ]
