# Generated by Django 4.2.4 on 2023-08-22 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0004_remove_user_data_storage_download_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_history_item',
            name='saved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='filtered_comments_history_item',
            name='saved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prompts_history_item',
            name='saved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferred_playlists_history_item',
            name='saved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
