# Generated by Django 4.2.4 on 2023-08-23 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0005_alter_download_history_item_saved_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_reset_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
