# Generated by Django 4.1.4 on 2023-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0005_user_data_storage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data_storage',
            old_name='name',
            new_name='object_name',
        ),
    ]
