# Generated by Django 4.1.4 on 2023-07-09 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0006_rename_name_user_data_storage_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_storage',
            name='prompts_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, size=None), default=['asdsada'], size=None),
            preserve_default=False,
        ),
    ]
