# Generated by Django 4.2.4 on 2023-08-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0007_alter_download_history_item_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download_history_item',
            options={'ordering': ['-id'], 'verbose_name': 'Download History Item', 'verbose_name_plural': 'Download History Items'},
        ),
        migrations.AlterModelOptions(
            name='filtered_comments_history_item',
            options={'ordering': ['-id'], 'verbose_name': 'Filtered Comments History Item', 'verbose_name_plural': 'Filtered Comments History Items'},
        ),
        migrations.AlterModelOptions(
            name='prompts_history_item',
            options={'ordering': ['-id'], 'verbose_name': 'Prompts History Item', 'verbose_name_plural': 'Prompts History Items'},
        ),
        migrations.AlterModelOptions(
            name='transferred_playlists_history_item',
            options={'ordering': ['-id'], 'verbose_name': 'Transferred Playlists History Item', 'verbose_name_plural': 'Transferred Playlists History Items'},
        ),
    ]
