# Generated by Django 4.1.4 on 2023-07-09 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0007_user_data_storage_prompts_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data_storage',
            name='prompts_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=None, size=None), size=None),
        ),
    ]
