# Generated by Django 4.1.4 on 2023-07-09 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0008_alter_user_data_storage_prompts_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_storage',
            name='filtered_comments_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, size=None), default=['asdas'], size=None),
            preserve_default=False,
        ),
    ]
