# Generated by Django 4.1.4 on 2023-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0009_user_data_storage_filtered_comments_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_storage',
            name='save_history',
            field=models.BooleanField(default=True),
        ),
    ]
