# Generated by Django 4.2.4 on 2023-08-26 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0009_alter_ticket_last_reset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_reset_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
