# Generated by Django 4.2.4 on 2023-08-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0012_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_data_storage',
            options={'verbose_name': "User's Storage", 'verbose_name_plural': "User's Storage"},
        ),
        migrations.RemoveField(
            model_name='user_data_storage',
            name='object_name',
        ),
    ]
