# Generated by Django 4.2.4 on 2023-08-18 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ythelperapp', '0013_alter_user_data_storage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_reset_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 0, 0)),
        ),
    ]
