name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements/requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTGRES_ENGINE: 'django.db.backends.sqlite3'
        POSTGRES_DB: 'youtube_helper_db'
        POSTGRES_USER: ''
        POSTGRES_PASSWORD: ''
        POSTGRES_HOST: ''
        POSTGRES_PORT: ''
        EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST: 'smtp.gmail.com'
        EMAIL_PORT: 587
        EMAIL_USE_TLS: True
        EMAIL_HOST_USER: 'YOUR EMAIL'
        EMAIL_HOST_PASSWORD: 'YOUR GMAIL APP PASSWORD'
        GOOGLE_API_KEY: 'YOUR API KEY'
        OPENAI_KEY: 'YOUR API KEY'
        SPOTIFY_CLIENT_ID: 'YOUR CLIENT ID'
        SPOTIFY_CLIENT_SECRET: 'YOUR CLIENT SECRET'
        SPOTIFY_REDIRECT_URI: 'YOUR REDIRECT URI'
        SPOTIFY_USERNAME: 'YOUR SPOTIFY USERNAME'
      run: |
        cd app
        python manage.py test
